### ISSUE TITLE
Add the ability to start a REPL

### ISSUE THREAD

**Issue by yuyichao** [JuliaEditorSupport/julia-emacs#1]
Ref https://github.com/JuliaLang/julia/issues/8715

> It need not be very sophisticated, and I'm not sure how we'll integrate the shell and help features, but basic functionality would be much better than nothing.

**Comment by tpapp** [comment]
ESS, which incorporates `julia-mode` from this repo, already has a sophisticated infrastructure for running a REPL.

**Comment by jballanc** [comment]
I think it would be nice to be able to use a Julia REPL independent of ESS, but at the same time I don't know that this belongs in `julia-mode`. Perhaps we need a separate project á là [cider](https://github.com/clojure-emacs/cider) for Clojure.

**Comment by tpapp** [comment]
I got tired of ESS and wrote a simple REPL interface for `julia-emacs`, using `term` in Emacs. Works fine for my purposes, basically allows sending code to the REPL, making sure there is one running. For everything else (completion, documentation, etc), you can use the REPL.

The whole thing is around 100 LOC and works fine for my purposes. The question is if I should submit a PR to julia-emacs, or make a separate git repo with the source.

PS: I believe that ESS is not ideal when you need more than the basic REPL it can handle. I faced this issue when I started using Gallium, which won't work inside ESS.

**Comment by tpapp** [comment]
Update: I did some cleanup and made my REPL code available at https://github.com/tpapp/julia-repl. It is a fairly simple minor mode for running along `julia-emacs`. Basically starts a REPL using `term`, and has some keybindings for sending code to it. For all the extras you use the REPL. I am now happy with this solution, as it allows me to use Julia with Gallium from inside Emacs.

**Comment by glycerine** [comment]
I concur with @tpapp 's thoughts.  

Any emacs mode for a language that has a REPL really should support interacting with the repl. 

I have an emacs mode, zjulia, which I've adapted to allow stepping through code from emacs buffer to julia repl as well. It would be lovely to have either @tpapp 's julia-repl or zjulia integrated with the julia-emacs mode for syntax highlighting. 

https://github.com/glycerine/zjulia-emacs-mode-julialang

**Comment by non-Jedi** [comment]
This was addressed in https://github.com/JuliaLang/julia/pull/10389 and can be closed I believe

**Comment by tpapp** [comment]
Yes, I agree, closing this.
