### ISSUE TITLE
Provide more highlight options

### ISSUE THREAD

**Issue by ronisbr** [JuliaEditorSupport/julia-emacs#103]
First of all, thanks for this amazing package! The support of Julia in Emacs is pretty good :)

However, I think there is a point that can be improved. For example, take a look at the following figure. To the left, there is a .jl file opened in Emacs, whereas, to the right, there is the same file opened in Vim.

![fig](https://user-images.githubusercontent.com/1068295/76690355-f04ec400-661d-11ea-8ea5-7401d71a5cd5.png)

Notice that Julia mode in Vim has many more highlight options compared to Emacs. It highlights operation symbols like `+`, `-`, `=` and also literals. I think it is a little bit better.

Question: is it possible to add those options in Emacs?

**Comment by ronisbr** [comment]
Please, forget about this. I enabled number highlighting using the package [highlight-numbers](https://github.com/Fanael/highlight-numbers) and emacs was **really** slow when opening files with a lot of numbers.

**Comment by non-Jedi** [comment]
It's certainly possible and might even be more efficient than what you experienced with highlight-numbers. Could you take a look at https://www.gnu.org/software/emacs/manual/html_node/elisp/Faces-for-Font-Lock.html and let me know which faces you'd like for these different kinds of highlighting?

**Comment by ronisbr** [comment]
> It's certainly possible and might even be more efficient than what you experienced with highlight-numbers. Could you take a look at https://www.gnu.org/software/emacs/manual/html_node/elisp/Faces-for-Font-Lock.html and let me know which faces you'd like for these different kinds of highlighting?

Nice! This is what I get with highlight-numbers:

<img width="655" alt="Captura de Tela 2020-03-17 às 21 29 34" src="https://user-images.githubusercontent.com/1068295/76913674-783f0300-6896-11ea-8420-3f47e9a35da6.png">

I think it is pretty good. It uses (AFAIK) `font-lock-constant-face` for the numbers. For the symbols, I would propose `font-lock-type-face`, which seems to be the same font used for `begin` and `end`.
