### ISSUE TITLE
Syntax coloring with-in `[ ]`

### ISSUE THREAD

**Issue by ode33** [JuliaEditorSupport/julia-emacs#104]
![image](https://user-images.githubusercontent.com/16816606/77117738-5f0e9180-6a11-11ea-948e-59b8f7956815.png)

The second `=` in `==` is not consistent. 

Thanks!

**Comment by ode33** [comment]
The error stems from the `for` operator. If can be triggered by simply typing `for ==` in Emacs.

**Comment by non-Jedi** [comment]
I'm pretty sure I broke this with the new highlighting of `=` in `for` expressions in #102. Sorry. Should be a simple fix.
