### ISSUE TITLE
Add support to org mode

### ISSUE THREAD

**Issue by ronisbr** [JuliaEditorSupport/julia-emacs#117]
It will be very good if we have support in org-mode to evaluate code just like we have in R, Java, and C. An initial work was created here https://github.com/gjkerns/ob-julia but the maintainer said he will not support the project anymore.

**Comment by non-Jedi** [comment]
I think this is out of scope for this project, but I've been using [ob-jupyter](https://github.com/dzop/emacs-jupyter#org-mode-source-blocks) very successfully for this purpose for the past year or so (just to let you know what options exist).

**Comment by ronisbr** [comment]
Nice! Thanks for pointing out. I will close this bug then :)
