### ISSUE TITLE
How to run `julia-repl` with sysimage

### ISSUE THREAD

**Issue by nesteiner** [JuliaEditorSupport/julia-emacs#131]
I have no patient in precompile package,so I create some .so file and I want to use `julia-repl` with this .so file  
how do i  do to set julia-repl command ,such as `julia --sysimage imagefile`, in spite of alias in bash  
thank you

**Comment by non-Jedi** [comment]
`julia-repl` is a separate emacs package from `julia-mode`. Any issues with it should be filed against its repo rather than this repo: https://github.com/tpapp/julia-repl.
