### ISSUE TITLE
Tab alignment 

### ISSUE THREAD

**Issue by brendanjmeade** [JuliaEditorSupport/julia-emacs#138]
Following up on a Zulip suggestion I'm opening this issue about tab indenting levels.  I've stumbled upon (created!) a case where Tab to align goes all the way back the column zero even when I'm indented in a function.  See:

https://github.com/brendanjmeade/Bem2d.jl/blob/master/examples/dislocationlayers.jl

Tab alignment works fantastically until approximately line 127.

**Comment by non-Jedi** [comment]
Without digging in too much, this looks like you just have waaay too long of a function, and it's causing the indenting engine to not look back far enough. Try increasing `julia-max-block-lookback`. Are you sure you're using a recent version of the major mode? The default value of that variable was increased in December...

**Comment by aramirezreyes** [comment]
Is this #5? This is a problem with the default maximum length of code block to be indented.

**Comment by brendanjmeade** [comment]
Got it and thank you.  Increased to 100k :) and it's working great!
