### ISSUE TITLE
Support linting

### ISSUE THREAD

**Issue by Nathan-Furnal** [JuliaEditorSupport/julia-emacs#140]
Hi!

Would it be possible to offer linting on save with Lint.jl or [`Julia-formatter`](https://github.com/domluna/JuliaFormatter.jl) ? On elpy (python support for emacs), there's the possibility to apply a linter to a buffer, coupled with `before-save-hook`, it makes linting quite easy.

Would that be an option for julia-mode ? 

Thanks

**Comment by tpapp** [comment]
I think that a dedicated minor mode would be better for that, unless there is code that can/needs to be shared with this mode.

**Comment by Nathan-Furnal** [comment]
Alright, I won't make any promises but I'll look into it!
