### ISSUE TITLE
Adding ! to the end of function name removes highlight

### ISSUE THREAD

**Issue by ronisbr** [JuliaEditorSupport/julia-emacs#141]
Hi!

The highlighting of a function with `!` at the end is not correct:

<img width="249" alt="Captura de Tela 2020-08-18 às 10 13 51" src="https://user-images.githubusercontent.com/1068295/90517251-84780680-e13b-11ea-92ca-a18eb6c9b319.png">

**Comment by non-Jedi** [comment]
Duplicate of #129 (which I can't reproduce). Would appreciate any help in identifying what interaction is causing this.

**Comment by ronisbr** [comment]
Sorry, this was 100% related to my inability to translate `!` to English :D

In my case, I am using Doom Emacs with doom-one theme.

**Comment by ronisbr** [comment]
I'm pretty sure that the problem is caused by this:

https://github.com/hlissner/doom-emacs/blob/c3520dd390b644c5f5a252f381435bf2e97f950c/modules/lang/julia/config.el#L10

A configuration inside Doom emacs. I am trying to verify.
