### ISSUE TITLE
What is the purpose of inferior-julia?  Gives "Text is read only" error when typing into it.

### ISSUE THREAD

**Issue by bgoodr** [JuliaEditorSupport/julia-emacs#144]
I'm referring to this function defined here:

https://github.com/JuliaEditorSupport/julia-emacs/blob/b5f5983d2b232c8bba4c5eff75cccdb787c19d98/julia-mode.el#L842

I've downloaded and installed Julia 1.5.1 into my home directory at ~/julia/julia-1.5.1/bin (Ubuntu 20.04), and have installed this package from MELPA using the construct in my Emacs setup of:

    (use-package julia-mode
      :ensure t
      :config
      ;; Set julia-program to the manually downloaded julia binary:
      (unless (boundp 'julia-program)
        (error "ASSERTION FAILED: Expected use-program to have bound julia-program by now by downloading it and installing it."))
      (let ((julia-install-dir "~/julia"))
        (when (file-directory-p julia-install-dir)
          (let ((dirs (directory-files
                       julia-install-dir
                       'full
                       (rx "julia-"
                           (+ (any "0-9" "."))
                           eol))))
            ;; Assume that only one version is installed, for now:
            (when (eq 1 (length dirs))
              (let ((julia-dir (car dirs)))
                (let ((potential-julia-program (expand-file-name "bin/julia" julia-dir)))
                  (when (file-executable-p potential-julia-program)
                    (setq julia-program potential-julia-program)))))))))

But when I execute M-x inferior-julia, I see this:

                   _
       _       _ _(_)_     |  Documentation: https://docs.julialang.org
      (_)     | (_) (_)    |
       _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
      | | | | | | |/ _` |  |
      | | |_| | | | (_| |  |  Version 1.5.1 (2020-08-25)
     _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
    |__/                   |

And when I type any character in that Emacs buffer, it gives the error:

    Text is read-only

Either this is user-error, or something is broken somehow.

I noticed that I do not see a prompt at all if I use M-x shell and then invoke the julia executable:

    $ ~/julia/julia-1.5.1/bin/julia
                   _
       _       _ _(_)_     |  Documentation: https://docs.julialang.org
      (_)     | (_) (_)    |
       _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
      | | | | | | |/ _` |  |
      | | |_| | | | (_| |  |  Version 1.5.1 (2020-08-25)
     _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
    |__/                   |
    
    1 + 1
    
    2
    
    
    $ 1

But, you now, of course it does show the prompt if I invoke a non-Emacs terminal window:

https://imgur.com/8d5gl9G

I call attention to the prompt, because I see that perhaps the Elisp code is looking for a prompt by defining `julia-prompt-regexp`, and not finding it for some reason, due to this variable definition:

https://github.com/JuliaEditorSupport/julia-emacs/blob/b5f5983d2b232c8bba4c5eff75cccdb787c19d98/julia-mode.el#L831

**Comment by non-Jedi** [comment]
Thanks for the bug report. This looks like Julia's fallback terminal in v1.5 no longer includes a "julia>" prompt (or something has changed in comint-mode). I'll look into it later. In general, I would recommend using one of the packages mentioned in #109 (probably either ess-julia, julia-repl, or emacs-jupyter) rather than inferior-julia.

**Comment by bgoodr** [comment]
Got it.  At this juncture, we don't know that this is caused by something misconfigured on my side.  So for reference, below is my Emacs version I'm using:

    GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.14) of 2020-03-26, modified by Debian

This is system package defined, not built from source.

**Comment by tpapp** [comment]
FWIW, you may be the only person using `inferior-julia` at this point, which is untested and pretty much unmaintained.

**Comment by bgoodr** [comment]
> FWIW, you may be the only person using `inferior-julia` at this point, which is untested and pretty much unmaintained.

@tpapp : You are probably correct.  I was trying it out only because the .el file in this package is what I was reading just to figure out how to use it, and it was then that I stumbled upon the `inferior-julia` stuff therein. I'm a brand-spankin' new user, and I don't know what I'm doing yet at all. :)  But I'm taking @non-Jedi's  advice and trying one of the ones that looks promising, from #109, specifically  the [julia-repl](https://github.com/tpapp/julia-repl/) mode.

My recommendation is to go with that theory, and just delete that feature and instead have people use one of the alternatives mentioned.

**Comment by tpapp** [comment]
I think we will obsolete this functionality soon, so I am closing this issue as the resolution is in #109.

**Comment by Inc0n** [comment]
inferior-julia can be made to work with some tweaks, but you still won't get the prompt back, even though the prompt is set properly:
> repl = Base.active_repl.interface.modes[1]
> "Prompt(\"julia> \",...)"

Is it not a concern as to why no prompts is showing in inf julia?

**Comment by Inc0n** [comment]
```
(defvar inf-julia-kept-output nil)
  ;; (setq inf-julia-kept-output nil)
  (let* ((buf (get-buffer "*Julia*"))
		 (process (get-buffer-process buf)))
	(set-process-filter (get-process "Julia")
						(lambda (process output)
						  (push output inf-julia-kept-output))))
```
if you run the following code, and simply press return in the inf julia. Nothing is showing yet, but `(ansi-color-apply (car inf-julia-kept-output))` will return this:
> "
> julia> 
>
> "

By reasoning, it's fair to say the process filter is being funny here, and investigating this further may be helpful to resolve this mystery.

**Comment by Inc0n** [comment]
I did some further testing, it seems that there is some sort of filtering (more likely from comint itself) interacting funnily with julia process output, this is the captured output:
"^[[?2004h
^[[0Kjulia> 
^[[7C
^[[7C"

**NOTE**: this is with `--color=no`

By reasoning, the julia process (under `--color=no` still outputs some sort of control codes?? which `comint` does not understand? and therefore filtered, including the "julia>" prompt.
Additionally by playing with `ansi-color`, it can be concluded this filtering is not done by `ansi-color`

**Comment by Inc0n** [comment]
From the issue I raise in julia https://github.com/JuliaLang/julia/issues/47837
Refering to https://discourse.julialang.org/t/julia-output-without-escape-sequences/65515.
The solution is to use `TERM=dumb`, except TERM is dumb. I have tried `setenv` `process-environment` to no avail. 

In julia, term=vt50.

**Comment by tpapp** [comment]
I don't think there is much interest in making inferior julia work, given the alternatives, but if you insist, you can start working on it in a separate package. It will be removed from this one soon. Cf #109.

Also, please open a new issue instead of commenting in closed ones unless there is a compelling reason.

**Comment by Inc0n** [comment]
The culprit is `comint-terminfo-terminal`, which is none other than `vt50` currently, therefore sticking this into my config solved the problem `(setq-default comint-terminfo-terminal 'dumb)`.

**Comment by Inc0n** [comment]
There is no issue to be raised here in my opinion (not anymore), I was reporting on the discoveries I found hoping that others may be able to help me. In the end I managed to solve this problem by chance. It was documented here: https://www.gnu.org/software/emacs/manual/html_node/emacs/Shell-Options.html.

**Comment by Inc0n** [comment]
@bgoodr Thanks. I learnt what tenacity means today 😅😄
