### ISSUE TITLE
Highlight of triple quote string with escaped quote

### ISSUE THREAD

**Issue by yuyichao** [JuliaEditorSupport/julia-emacs#15]
The triple quote string is not highlighted correctly if there's another triple quote in the string that has only the first quote escaped.

Screenshot,
![spectacle x15522](https://cloud.githubusercontent.com/assets/712232/14566350/422393c4-02fd-11e6-8b46-33592f82b943.png)
The first line is highlighted correctly but the second one not.

**Comment by rfourquet** [comment]
Related: highlight of a single quote string with ecaped quotes fails: `"a\"b"`.

**Comment by christopher-dG** [comment]
Also related, all text following this string is highlighted as part of the string:

`"""he said: "hello, world\""""`
