### ISSUE TITLE
Can someone put in the README how to change the font colors (or a pointer thereto)?

### ISSUE THREAD

**Issue by jeffshrager** [JuliaEditorSupport/julia-emacs#156]
The bright red comments are burning themselves into my retina. To each their own, of course, but I'd like to know how to self-mod this (and other colors) so that I can save my retinas. (I got as far as printing out the value of julia-font-lock-keywords, and, as you can probably guess, came straight here! :-) Thanks!

**Comment by non-Jedi** [comment]
You can simply customize the `font-lock-comment-face`. For other colors, you will want to do <kbd>M-x</kbd> `customize-group` on `font-lock-faces`. Alternatively, I recommend finding a better emacs theme that doesn't make comments red.

**Comment by jeffshrager** [comment]
kk. Thanks!
