### ISSUE TITLE
ERROR: syntax: invalid identifier name "?" .  ERROR: syntax: unexpected "]"

### ISSUE THREAD

**Issue by rdiaz02** [JuliaEditorSupport/julia-emacs#157]
In the inferior julia process, typing `?` gives  `ERROR: syntax: invalid identifier name "?"`  and typing `]` gives `ERROR: syntax: unexpected "]" `.

This happens to me under both Emacs 27.1 and Emacs 28 (with native compilation), using both julia-mode 20210323.612 from Melpa and julia mode from the just cloned repo.  

**Steps to reproduce with julia-mode from Melpa:**
1. `emacs -Q`
2.   `C-x e`
```
        (require 'package)
        (package-initialize)
        (require 'julia-mode)
```
3. `M-x run-julia`
4. Type `?` . Type `]`
```
julia> ?
ERROR: syntax: invalid identifier name "?"
Stacktrace:
 [1] top-level scope
   @ none:1

julia> ]
ERROR: syntax: unexpected "]"
Stacktrace:
 [1] top-level scope
   @ none:1
```

**Steps to reproduce with julia-mode from the cloned repo:**
1. `emacs -Q`
2.   `C-x e`
```
      (add-to-list 'load-path "path_to_julia-emacs")
      (require 'julia-mode)
```
3. `M-x run-julia`
4. Type `?` . Type  `]`

**Also possibly related error with ESS**
In addition, if also running ESS (e.g., when using steps to reproduce with julia model from Melpa, use `M-x run-ess-julia` instead of `M-x run-julia`), typing, say `??` gives `ess-display-help-on-object: Invalid function: (inferior-ess-primary-prompt . "\\w*> ")`.  (This issue has been mentioned here: https://github.com/emacs-ess/ESS/issues/1151 )

**Comment by tpapp** [comment]
The inferior-julia in this package is not really supported and there are plans to remove it, see #109.

**Comment by rdiaz02** [comment]
Thanks for the reply, and sorry for missing #109. And, yes, indeed, using julia-repl (https://github.com/tpapp/julia-repl) or julia-vterm (https://github.com/shg/julia-vterm.el) work just fine for me.

**Comment by tpapp** [comment]
Closing (in favor of #109).
