### ISSUE TITLE
indentation with the comment characters and the pipe operator

### ISSUE THREAD

**Issue by tcovert** [JuliaEditorSupport/julia-emacs#19]
This indents just fine:
df = @linq df |>
transform(x = ismatch(r"[ ]*?([\d]{1,5})", :text)) |>
transform(y = :x \* 2)

This does not:
df = @linq df |>
transform(x = ismatch(r"#[ ]*?([\d]{1,5})", :text)) |>
transform (y = :x \* 2)

**Comment by non-Jedi** [comment]
For reference, the problematic behavior is that `#` in strings affect
indentation. Current behavior is:

``` julia
a = "a" |>
    identity

b = "#" |>
identity
```
