### ISSUE TITLE
julia-mode.el not indenting and throwing error

### ISSUE THREAD

**Issue by Inaki-Ulibarri** [JuliaEditorSupport/julia-emacs#203]
julia-mode throws an error when trying to indent code in emacs 28. 2. This is similar to issue #183, but reinstalling didn't work in this case.

Here are the logs from `Async-native-compile-log`

```
In julia--regexp-opt:
julia-mode.el:71:8: Warning: docstring wider than 80 characters

In julia-last-open-block-pos:
julia-mode.el:458:35: Warning: Unused lexical variable `cl-count'
julia-mode.el:472:14: Warning: reference to free variable ‘count’
julia-mode.el:469:33: Warning: assignment to free variable ‘count’

In julia-end-of-defun:
julia-mode.el:737:4: Warning: Unused lexical argument `arg'
julia-mode.el:737:4: Warning: Unused lexical variable `beg-pos'

In inferior-julia:
julia-mode.el:908:12: Warning: Unused lexical variable `buffer'
Compilation finished.
```

**Comment by non-Jedi** [comment]
Could you post detailed instructions for getting the error to throw as well as the backtrace from `M-x toggle-debug-on-error` please?

**Comment by Inaki-Ulibarri** [comment]
Sure, just write any expression that can be indented, such as 
```
for _ in 1:5
println(":D")
end
```
and press tab in the indentable body of the expression (println).

The backtrace is:
```
Debugger entered--Lisp error: (void-variable count)
  julia-last-open-block-pos(1)
  julia-last-open-block(-4987)
  julia-indent-line()
  indent--funcall-widened(julia-indent-line)
  indent-for-tab-command(nil)
  julia-latexsub-or-indent(nil)
  funcall-interactively(julia-latexsub-or-indent nil)
  command-execute(julia-latexsub-or-indent)
```

**Comment by non-Jedi** [comment]
See #190. Not sure how you installed `julia-mode`, but you can't be using the latest version with that backtrace.

**Comment by Inaki-Ulibarri** [comment]
Ah, it's always the cache fuckery with package loading :p. I really need to start putting this machine to rest once in a while. I'll close the issue and thanks for your time.

**Comment by non-Jedi** [comment]
It's one of the reasons I like straight.el. It downloads git repos for each package and then builds the package in a separate directory. Each time emacs starts it rebuilds all packages that have been changed in their git repo. In practical terms, it means that I've had no trouble with accidentally using an outdated `.elc` since I started using it as my package manager. :)
