### ISSUE TITLE
Help finding a maintainer for julia-ts-mode

### ISSUE THREAD

**Issue by ronisbr** [JuliaEditorSupport/julia-emacs#205]
Hi everyone!

As some of you might know, I have been developing a Julia major mode for Emacs using tree-sitter here: https://github.com/ronisbr/julia-ts-mode

However, I have switched sometime ago to Neovim as my main text editor. Hence, I have very little time to debug and improve `julia-ts-mode`. IMHO, the best thing to do would be transferring the package to JuliaEditorSupport org so that the package can continue to improve.

Is it possible to do that? If so, how can we do that? The package is registered in MELPA.

**Comment by ronisbr** [comment]
Thanks @tpapp !

That would be the best approach. However, given the lack of manpower, wouldn't it be better to transfer the package first and then verify how it can be merged? The current version of `julia-ts-mode` lacks important things, like tests.

**Comment by non-Jedi** [comment]
I think migrating `julia-ts-mode` to the "JuliaEditorSupport" organization makes sense as an intermediate step before merging it into this repo. And, as I understand it, github will redirect `github.com/ronisbr/julia-ts-mode` to `github.com/JuliaEditorSupport/julia-ts-mode` as long as @ronisbr doesn't create a new repo with the name `julia-ts-mode`. So the steps would be:

1. Transfer `julia-ts-mode` to `JuliaEditorSupport`.
2. Create melpa pull request changing URL for `julia-ts-mode`.
3. Over time, merge `julia-ts-mode` into this repo.
4. Not sure of an elegant way to migrate melpa for merging packages, but something probably exists.

I'll go ahead and initiate the transfer as long as @tpapp is aligned with this plan?

**Comment by tpapp** [comment]
Yes, I think this is a good idea.

**Comment by ararslan** [comment]
Done

**Comment by ronisbr** [comment]
Done! The MELPA PR was merged. Now, we can continue the development of `Julia-ts-mode` here :)

**Comment by tpapp** [comment]
@ronisbr: Thanks for transferring, and all the great work you have done. I am closing this issue since I consider maintainership resolved, the maintainers of julia-emacs will now do it.
