### ISSUE TITLE
Error during redisplay: (jit-lock-function 1) signaled (error "prism: Infinite loop detected in ‘prism-match’.  Please report this bug")

### ISSUE THREAD

**Issue by YueRen** [JuliaEditorSupport/julia-emacs#211]
Recently, I've started running into difficulties using julia-mode in combination with [prism](https://github.com/alphapapa/prism.el).

On my machine, prism-mode struggles with the following minimal julia file:

```
"""asdf
    qwer
"""
sum([1,2])
```

It raises the following error in the `*Messages*` buffer:

```
Error during redisplay: (jit-lock-function 1) signaled (error "prism: Infinite loop detected in ‘prism-match’ (buffer:#<buffer mwe.jl> point:2).  Please report this bug")
```

However, I don't think this is an error in prism-mode, as it is perfectly fine with the following multi-line comment in python (where julia-mode is inactive):
```
"""asdf
   qwer
"""
print("Welcome to Scaler!")
```

**Comment by non-Jedi** [comment]
Hi @YueRen. Please report this to prism or provide more detail on how this is a bug in julia-mode (e.g. a stacktrace showing how julia-mode is *incorrectly* causing an infinite loop in `prism-match`). We aren't in a position to be figuring out why an external package is raising an error without more information than this.

**Comment by YueRen** [comment]
@non-Jedi Sorry for the late reply.  This indeed seems more like a bug with prism, so I will close this ticket for now.  I may reopen this, in case something in julia-mode is causing the failure and I figure out what.

**Comment by YueRen** [comment]
Minor update, I was using `prism-mode` wrongly.  In case anybody runs into the same error, here is the solution:
https://github.com/alphapapa/prism.el/issues/29#issuecomment-2132594451
