### ISSUE TITLE
Transfer repo to https://github.com/JuliaEditorSupport/

### ISSUE THREAD

**Issue by ViktorQvarfordt** [JuliaEditorSupport/julia-emacs#22]
Given that JuliaLang is getting crowded, packages are being moved to more appropriate places, such as JuliaMath, JuliaWeb, etc. Editor support repos are being moved to JuliaEditorSupport.

**Comment by tkelman** [comment]
I plan on doing this if no one objects. I invited @Wilfred @yuyichao and @stevengj to that organization. Any reason not to do this?

**Comment by Wilfred** [comment]
No objections from me. We'll need to update the MELPA recipe to build Emacs packages from the new URL, but that's easy.

**Comment by tkelman** [comment]
Cool. And the github auto-redirects should handle things smoothly before the URL gets changed in MELPA, I would think.

**Comment by tkelman** [comment]
Done, thanks.
