### ISSUE TITLE
Tab indentation fails

### ISSUE THREAD

**Issue by jameskermode** [JuliaEditorSupport/julia-emacs#23]
Error message when indenting code by pressing Tab is `Symbol's function definition is void: looking-at-p`.

This is the same problem as issue #16, however I'm not on OS X but on a Linux server where I cannot easily upgrade emacs from version 22.3.1 - is there a workaround possible?

**Comment by tpapp** [comment]
You can always compile an Emacs from source in your home directory. Emacs 22 is ancient, many things have changed since, and supporting it is a huge undertaking. Even supporting 24 and 25 at the same time is costly.

**Comment by non-Jedi** [comment]
I believe this can be closed as emacs 22 is not supported.

**Comment by rfourquet** [comment]
Yes, as emacs 23 is about to stop being supported.
