### ISSUE TITLE
wrapping control statements in parenthesis leads to wrong indentation

### ISSUE THREAD

**Issue by jshysing** [JuliaEditorSupport/julia-emacs#27]
I prefer to wrap control statements in parenthesis, however this seems to break the indentation like in the following example ( applying end() seems to fix the issue but that's obviously not a nice fix)

```julia
if( a>0 )
end

    for( i=1:2 )
        for( j=1:2 )
            for( k=1:2 )
            end
            end
        end

        end

```

**Comment by yuyichao** [comment]
Likely dup of https://github.com/JuliaEditorSupport/julia-emacs/issues/10
