### ISSUE TITLE
indentation fails with the \ function

### ISSUE THREAD

**Issue by rfourquet** [JuliaEditorSupport/julia-emacs#40]
This comes from the current "deprecated.jl" file:
```
_promote_array_type(::typeof(\), ::Type{<:Integer}, ::Type{<:Integer}, T::Type) = T
                    this_line_is_not_correctly_indented()

**Comment by yuyichao** [comment]
Should be fixed by https://github.com/JuliaEditorSupport/julia-emacs/pull/37 already.

**Comment by rfourquet** [comment]
Ah yes sorry, for some reason my running instance of emacs which had been loading an older version of julia-mode (before #37 was merged) doesn't indent correctly even after re-loading an up-to-date version of julia-mode, so I didn't notice.
