### ISSUE TITLE
Edit docstrings with markdown-mode

### ISSUE THREAD

**Issue by non-Jedi** [JuliaEditorSupport/julia-emacs#50]
Would be really nice if julia-mode provided ability to edit docstrings using
markdown-mode. Not an elisp guy, and still a relatively new emacs user, so I'm
not sure exactly how this would work, but I thought I'd throw the suggestion out
there.

Maybe if I get some time, I'll take a look at how org-mode does it with src
blocks and see if I can duplicate that in julia-mode.

**Comment by Schroedingberg** [comment]
I think this would be a really nice feature to have.
In order to avoid reinventing the wheel, may I suggest to attempt adapting the following package for this purpose:
https://github.com/glyph/python-docstring-mode

This defines a minor mode which is then just hooked to the respective python major mode, allowing to edit python docstrings using rst or spinx syntax.

If there are no objections to this strategy, I would be delighted to start working on this.

**Comment by tpapp** [comment]
@Schroedingberg: how does that work? Would it automatically recognize a docstring and switch modes?

The other solution I am aware of is https://github.com/polymode/polymode .

**Comment by non-Jedi** [comment]
I took a more in-depth look at this today (since I'm much more proficient in emacs/elisp than I was 2 years ago).

`python-docstring-mode` just has a bunch of regexes that it applies to the whole buffer and assumes won't collide with fontification outside of docstrings. I don't think this is a good approach.

org-mode fontifies `#+BEGIN_SRC` blocks basically by copying the contents of that block to a temporary buffer, having the language major mode fontify that buffer, and then copying the text properties from that buffer back into the block being fontified. This is a viable approach for julia, but it feels a bit flimsy. I think a package doing so should probably live outside `julia-mode`; it also doesn't provide other features of markdown-mode (e.g. indentation).

Depending on poly-mode or mmm-mode is probably the best solution, but I don't think it's desirable to have `julia-mode` depend on packages external to emacs, so an implementation using them would probably best live as an external package if possible. [poly-org](https://github.com/polymode/poly-org/blob/master/poly-org.el) is an interesting demo showing that integration with polymode can be accomplished in only a few lines of code so long a you have robust matchers for the start and end of the region (may be a problem for julia since matchers need to do backtracking).

**Comment by tpapp** [comment]
Yes, I think a package depending on this one and defining a minor mode would be ideal.
