### ISSUE TITLE
Keyword type --> struct

### ISSUE THREAD

**Issue by liltaylor** [JuliaEditorSupport/julia-emacs#52]
keyword "type" is now (julia v. 0.6) deprecated, substituted by "struct"

please at least add keyword "struct"

also "immutable" is deprecated

**Comment by WangWei90** [comment]
yes, I also think this julia-mode should sync with melpa (there has been a long time without update on melpa)

**Comment by non-Jedi** [comment]
Closed by #36

**Comment by tpapp** [comment]
Thanks for noticing this.
