### ISSUE TITLE
julia-mode and org html export with background

### ISSUE THREAD

**Issue by vincent-picaud** [JuliaEditorSupport/julia-emacs#53]
When html-exporting this Org mode example.org (with C-c C-e h o):

```
#+HTML_HEAD_EXTRA: <style type="text/css"> blockquote {background:#EEEEEE; padding: 3px 13px}    </style>
#+HTML_HEAD_EXTRA: <style type="text/css"> pre {background:#EEEEEE; padding: 3px 13px}    </style>

Some text...

#+BEGIN_EXAMPLE
:: or <: ?
#+END_EXAMPLE

#+BEGIN_SRC julia 
abstract type A end
struct S <: A
   x::T
end
#+END_SRC
```

I get this:
![julia-mode-problem](https://user-images.githubusercontent.com/5292307/38289554-0a5caea6-37d7-11e8-852b-1498ad4d33f1.png)

I think that there is a problem in the way the "::" and "<:" char sequences are processed, in julia-mode.el one can read:
```
(defconst julia-font-lock-keywords
  (list
   ;; Ensure :: and <: aren't highlighted, so we don't confuse ::Foo with :foo.
   ;; (in Emacs, keywords don't overlap).
   (cons (rx (or "::" "<:")) ''default)
   ...
```

If I comment this line:
```
   ;; (cons (rx (or "::" "<:")) ''default) 
```
and export again example.org with Org, I get now:
![julia-mode-ok](https://user-images.githubusercontent.com/5292307/38289726-ebedf21c-37d7-11e8-933b-c682ebd73280.png)
which is fine.

Commenting the line is quite brutal and certainly has side effect. 
Sure you will find a more elegant solution :-)

**Comment by tpapp** [comment]
Sorry for allowing this issue to languish for so long.

Thanks for the nice MWE, actually I am not sure if simply removing the line
```emacs-lisp
(cons (rx (or "::" "<:")) ''default) 
```
would break anything. What side effects do you notice?

**Comment by vincent-picaud** [comment]
I hadn't given up hope :-) 

At the time, I hadn't noticed any side effects (for my local installation the mentioned line was commented). I think it  can be removed.

Best,
-- Vincent
