### ISSUE TITLE
My custom theme fails to highlight the variable names

### ISSUE THREAD

**Issue by fincardona** [JuliaEditorSupport/julia-emacs#57]
Hello, 
I usually use a custom theme where the variable names are highlighted in orange. I do it by putting the command `'(font-lock-variable-name-face ((t (:foreground "orange red"))))` in my `custom-theme.el` file and it works when I write python code. However, it apparently fails whit julia-mode. Do you have any suggestions? 
Thanks a lot.

**Comment by non-Jedi** [comment]
See also #77

This mode doesn't currently look for variable assignment in `julia-font-lock-keywards`. If you are interested in adding this functionality, the implementation for python in "progmodes/python.el" which came with your emacs distribution looks like a reasonable place to start.

**Comment by non-Jedi** [comment]
Duplicate of #2. Can be closed.

**Comment by tpapp** [comment]
Yes, closing this as a duplicate.
