### ISSUE TITLE
\( upsets paren matching

### ISSUE THREAD

**Issue by tpapp** [JuliaEditorSupport/julia-emacs#58]
![screenshot_2018-12-03_09-27-06](https://user-images.githubusercontent.com/84122/49361967-a28aa280-f6dd-11e8-856f-2bf514f09f17.png)

Using `julia-emacs` `master`, Emacs 26.1.

**Comment by galenlynch** [comment]
I just run across this when using regexs:
```julia
r"\"\(([^\)]+)\)\""
```
should capture the contents inside the parentheses of a string like `"(foo bar)"`, but it messes up julia-mode.

**Comment by non-Jedi** [comment]
For reference, this is the same underlying problem as #59.
