### ISSUE TITLE
(\)(2, 4) upsets auto-indent

### ISSUE THREAD

**Issue by jlapeyre** [JuliaEditorSupport/julia-emacs#59]
The following
```
(\)(2, 4)
```
breaks auto-indent on subsequent lines.

The following, does *not*
```
\(2, 4)
```

I got *julia-mode.el* from elpa. But, the file is identical to the master branch here, except for a comment.

**Comment by tpapp** [comment]
I can confirm on `julia-mode` master. It breaks by 1 character:

```julia
(\)(2, 4)

 following_code
```

**Comment by tpapp** [comment]
`syntax-ppss` thinks that it is inside the first `(`, not noticing the `\)`. I will try to dig into this but if someone is familiar with Emacs syntax tables, help would be appreciated.

@giordano, @non-Jedi, @FelipeLema?

**Comment by non-Jedi** [comment]
It's because `\` has the "escape" syntax class to make escaping work correctly in strings. It's what I tried to fix in #85. If you remove it, examples like this one or #58 work correctly, but `"\"'` doesn't. For reference on how to fix, the builtin `octave-mode` is good.

**Comment by tpapp** [comment]
Yes, if you have looked into this it would be great if you could tackle it.

**Comment by tpapp** [comment]
@non-Jedi, does this mean you intend to do a rewrite with SMIE?

**Comment by non-Jedi** [comment]
No. Not for this issue. SMIE doesn't really help.
