### ISSUE TITLE
`∈` not highlighted in `for var ∈  …`

### ISSUE THREAD

**Issue by FelipeLema** [JuliaEditorSupport/julia-emacs#71]
The `in` in `for var in  …` is highlighted as keyword.
The `∈` in `for var ∈  …` is not highlighted as keyword.

**Comment by FelipeLema** [comment]
Implementation-wise it's a different story, though.

`in` is highlighted because it's part of "for each loop", see `julia-forloop-in-regex`

**Comment by yuyichao** [comment]
Removing it has no effect AFAICT.

**Comment by FelipeLema** [comment]
`julia-forloop-in-regex` is part of `julia-font-lock-keywords`.

I don't mind removing it, as long as it keeps fontification consistent.
