### ISSUE TITLE
multi-line lambda not indented correctly as function parameter

### ISSUE THREAD

**Issue by FelipeLema** [JuliaEditorSupport/julia-emacs#73]
Expected

    lines=[]
    Channel(c->begin
            for l in lines
            for w in split(l)
            put!(c, w)
            end
            @show l
            end
            end)
    
Got

    lines=[]
    Channel(c->begin
            for l in lines
                for w in split(l)
                    put!(c, w)
                end
                @show l
            end
            end)

Do mind that I'm asking for the lambda code to be *indented the same* as its declaration (at `c` parameter). This is why the last two `end` are aligned.

This same-indenting may not be consistent, but I don't think so. If it is, I'll change the example.

**Comment by FelipeLema** [comment]
As reference, declaring the lambda outside works as expected (do mind that it indents to `ƒ` and not `c`)

    ƒ=c->begin
        for l in lines
            for w in split(l)
                put!(c,w)
            end
            @show l
        end
    end
    Channel(ƒ)

**Comment by yuyichao** [comment]
I assume you reversed the expected and got and this is dup of https://github.com/JuliaEditorSupport/julia-emacs/issues/11, unrelated to anonymous functions
