### ISSUE TITLE
Syntax Highlight

### ISSUE THREAD

**Issue by ghost** [JuliaEditorSupport/julia-emacs#77]
I'm using this mode with the default Emacs theme and it doesn't highlight variables when performing assignments. Is this behavior intended?

For example:
`x  = 2`

Shouldn't `x` have be highlighted?

**Comment by tpapp** [comment]
I don't think that this is intended to be highlighted. A good starting point for code for highlighting is [here](https://github.com/JuliaEditorSupport/julia-emacs/blob/ad6a4944feb61f5c7238cfaf6c99ae63544315c2/julia-mode.el#L308), and there is no regex for variable assignments, only for short-form function definitions like `f(x) = x + 1`.

I checked ESS's Julia mode, and it does not highlight assignments either.

**Comment by non-Jedi** [comment]
Duplicate of #2. Can be closed.

**Comment by tpapp** [comment]
Closing this as a duplicate.
