### ISSUE TITLE
add collaborators?

### ISSUE THREAD

**Issue by tpapp** [JuliaEditorSupport/julia-emacs#79]
Many PRs for this repo get no attention or very delayed feedback.

Please consider adding volunteers who are active users of this code (ie Emacs & Julia) and would be willing to contribute (I would be happy to do it, I am sure there are other past contributors who would join).

**Comment by tpapp** [comment]
@JeffBezanson @Wilfred @ViralBShah @StefanKarpinski @stevengj 

I am pinging you as the top 5 contributors to this package. I don't know if you are still using Emacs, but you are all core contributors to Julia so it is understandable if you have less time for Emacs support. 

However, there are some nice PRs that have been getting little attention, some for years. I have started reviewing them and would like to move forward with merging, if given permission. I think that there are quite a few Julia users who rely on Emacs, and some of them would have some bandwidth for this code, but PRs languishing for a long time without feedback doesn't motivate contributions.

As I said above, I would be happy to do this, but the important thing is that you just add *someone* who is willing to manage this repository. You could also ask on the Discourse forum for volunteers.

**Comment by rfourquet** [comment]
I support @tpapp's request, and think he would be a great co-maintainer of this repo. I also volunteer (but not to be the only one ;-) ).

**Comment by ViralBShah** [comment]
I invited both @rfourquet and @tpapp. Please accept the invitations.

**Comment by rfourquet** [comment]
Thanks Viral!

**Comment by tpapp** [comment]
Thanks, closing the issue. And with @rfourquet, we will hopefully close a few other issues too :wink:
