### ISSUE TITLE
RFC: drop support for Emacs 23

### ISSUE THREAD

**Issue by tpapp** [JuliaEditorSupport/julia-emacs#86]
Supporting only Emacs 24 and above would have the following advantages:

1. simpler CI setup (cf #84)

2. ability to use `cl-lib` (instead of `cl` as we currently do, cf #60).

Please comment on this, especially if you need Emacs 23. As developers are usually on the bleeding edge, it is easy to forget about users operating in legacy environments.

Some data:

- Emacs 24.1 was released on 2012-06-10,

- the oldest Ubuntu LTS supporting Emacs 24 is Trusty (2014-04), other distributions have a similar timeline

**Comment by tpapp** [comment]
Discussion topic: https://discourse.julialang.org/t/dropping-support-for-emacs-23-in-julia-emacs/31001

**Comment by tpapp** [comment]
@giordano, since you are the maintainer of AUCTeX which supports Emacs 24+, I would value your opinion about this.

**Comment by giordano** [comment]
AUCTeX tends to be conservative when it comes to support of old platforms, yet I don't think we've got complaints from Emacs 23- users after we started requiring 24+.  Supporting only more recent versions has been very useful for us to drop quite a lot of backward-compatibility code.

**Comment by tpapp** [comment]
We should probably address #46 (ie make a release) before dropping support for Emacs 23, so that legacy users can still find a working version easily.

**Comment by tpapp** [comment]
A relevant comment from this discussion: https://github.com/JuliaEditorSupport/julia-emacs/pull/66#issuecomment-451620916

As far as I understand, CentOS 6 support is no longer implied since Julia now needs GCC version 4.7 or later.

**Comment by ffevotte** [comment]
Even at work where we tend to have rather old versions of everything, we got emacs-24 in our latest environment deployment.

**Comment by tpapp** [comment]
It turns out MELPA prefers lexical bindinging by default, so we need to do this before that.

**Comment by tpapp** [comment]
I would like to thank everyone for the feedback. It seems that dropping Emacs 23 is unanimously supported, which is great as it would make maintaining and improving this package easier.

I am proposing that we wait a month, specifically until Dec 12, to allow more users to comment, then just drop Emacs 23.
