### ISSUE TITLE
Shouldn't the installation procedure be described?

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaEditorSupport/julia-emacs#89]
Shouldn't the README describe how to install the Julia mode? To me (as a non-expert) it is not clear how to do it. Which files are needed, where to put them, and so on.

**Comment by tpapp** [comment]
I think that MELPA should be the distribution channel for most people, once we fix #46.

**Comment by PetrKryslUCSD** [comment]
Sounds good.
