### ISSUE TITLE
Looks for julia-latexsubs in directory of file in current buffer

### ISSUE THREAD

**Issue by chriselrod** [JuliaEditorSupport/julia-emacs#91]
On julia-mode 20191128.1452, if (for example) I open the file
`/home/username/.julia/dev/MyPackage/src/foo.jl`
I get the following error:

`File mode specification error: (file-missing Cannot open load file No such file or directory /home/myusername/.julia/dev/MyPackage/src/julia-latexsubs)`

After this, there is no syntax highlighting or other expected functionality.

This is on Cygwin. I could try Linux later if no one can reproduce on Linux.

**Comment by non-Jedi** [comment]
See https://github.com/JuliaEditorSupport/julia-emacs/pull/83#issuecomment-560211950 for context

**Comment by chriselrod** [comment]
> This seems to cause issues with lazy-loading packages (e.g. in doom-emacs). 

I'm on regular emacs. Is there a way to load julia-mode so that things can work for now?
Currently, I have
```elisp
(require 'julia-repl)
(add-hook 'julia-mode-hook 'julia-repl-mode)
```
