### ISSUE TITLE
julia-mode breaks prettify-symbols for auctex

### ISSUE THREAD

**Issue by mattblackwell** [JuliaEditorSupport/julia-emacs#99]
When julia-mode is loaded during init, prettify-symbols-mode is broken for auctex. I can reproduce this by calling `emacs -q --load "init-bug.el"`, where `init-bug.el` is:

    (package-initialize)
    (global-prettify-symbols-mode t)
    (require 'julia-mode)

Then, I `C-x C-f mwe.tex` where `mwe.tex` is:

    \documentclass{article}
    \begin{document}    
    \[
    \alpha \times \beta 
    \]
    \end{document}

What you should see is the unicode characters replacing alpha, times and beta, but with that init file, no prettifying occurs. If you remove the `(require 'julia-mode)` line from the init file, prettifying works just fine. I believe the issue is the call to `(require 'latex nil t)` on line 836 of `julia-mode.el`. That appears to load auctex outside of when it doesn't expect to be loaded, which sets the prettify alist to nil. I believe (thought am not totally sure) that you can achieve the same test without loading auctex by using `(featurep 'latex)` in place of that require call. 

Emacs version: 26.1
julia-mode version: 20191225.858

**Comment by tpapp** [comment]
Thanks for the very nice MWE, and sorry for the delay in getting back to you.

I can reproduce this, and I believe that your analysis is correct.

Can you make a PR that fixes this?

**Comment by mattblackwell** [comment]
Yep, done.
